-- Baseline migration: brings any pre-existing Easy OEE database up to the
-- current schema as of 2026-04-07 (Tier 1-4 batch).
--
-- All statements are IF NOT EXISTS so this is safe to apply to a database
-- that already has these columns (e.g. the Neon dev branch where they were
-- pushed manually via scripts/apply-tier-migrations.mjs).
--
-- Future migrations will be generated by `pnpm db:generate` and won't need
-- to be idempotent — the runner in scripts/migrate.mjs tracks which files
-- have been applied via the _eo_migrations table.

ALTER TABLE company ADD COLUMN IF NOT EXISTS timezone text NOT NULL DEFAULT 'America/Toronto';
--> statement-breakpoint
ALTER TABLE line ADD COLUMN IF NOT EXISTS target_oee numeric(5,4) NOT NULL DEFAULT 0.85;
--> statement-breakpoint
ALTER TABLE line ADD COLUMN IF NOT EXISTS board_token text;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'line_board_token_unique'
  ) THEN
    ALTER TABLE line ADD CONSTRAINT line_board_token_unique UNIQUE (board_token);
  END IF;
END $$;
--> statement-breakpoint
ALTER TABLE shift ADD COLUMN IF NOT EXISTS ending_operator_id uuid REFERENCES "user"(id);
